#! /usr/bin/env python
# Copyright 2018 Martin C. Frith

from __future__ import print_function

import gzip
import itertools
import optparse
import signal
import subprocess
import sys

def myOpen(fileName):
    if fileName == "-":
        return sys.stdin
    if fileName.endswith(".gz"):
        return gzip.open(fileName)
    return open(fileName)

def complement(x):
    return "TGCA"["ACGT".index(x)]

def reverseComplement(seq):
    return "".join(map(complement, reversed(seq)))

def isRepeatedCodons(seq, codons):
    r = range(0, len(seq), 3)
    return all(seq[i:i+3] in codons for i in r)

def isRepeatedCodonsInAnyFrame3(seq, codons):
    return any(isRepeatedCodons(seq[i:] + seq[:i], codons) for i in range(3))

def isRepeatedCodonsInAnyFrame6(seq, codons):
    if isRepeatedCodonsInAnyFrame3(seq, codons):
        return True
    codons = [reverseComplement(i) for i in codons]
    return isRepeatedCodonsInAnyFrame3(seq, codons)

def isBadCodons(seq):
    glnCodons = "CAA", "CAG"
    alaCodons = "GCA", "GCC", "GCG", "GCT"
    badCodonSets = glnCodons, alaCodons
    return any(isRepeatedCodonsInAnyFrame6(seq, i) for i in badCodonSets)

def changesFromText(text):
    if text != ".":
        for i in text.split(","):
            yield int(i.split(":")[0])

def readTandemGenotypes(opts, fileNames):
    repeatLengthBoost = 30  # xxx ???
    partScores = {"coding": 50, "5'UTR": 20, "3'UTR": 20, "exon": 15,
                  "promoter": 15, "intron": 5}
    for fileName in fileNames:
        for line in myOpen(fileName):
            fields = line.split()
            if not fields or line[0] == "#":
                continue
            chrom, beg, end, rep, geneName, genePart, fwd, rev = fields
            beg = int(beg)
            end = int(end)
            repLen = end - beg
            unitLen = len(rep)
            fwd = sorted(changesFromText(fwd))
            rev = sorted(changesFromText(rev))
            both = sorted(fwd + rev)
            change2 = 0
            if len(both) > 1:
                change2 = max(0, both[-2], -both[1])
            percent = unitLen * change2 * 100 // (repLen + repeatLengthBoost)
            geneScore = partScores.get(genePart, 1)
            if genePart == "coding" and isBadCodons(rep):
                geneScore *= 2
            score = geneScore * percent
            if opts.verbose:
                print(chrom, beg, end, rep, geneName, genePart,
                      change2, geneScore, score, sep="\t")
            yield score, chrom, beg, end, rep, geneName, genePart, fwd, rev

def binsFromSortedValues(values):
    maxBins = 50  # xxx ???
    minVal = values[0]
    maxVal = values[-1]
    for s in itertools.count():
        step = s * 2 + 1
        offset = step // 2
        binBeg = (minVal + offset) // step
        binEnd = (maxVal + offset) // step + 1
        if binEnd - binBeg <= maxBins:
            beg = binBeg * step - offset
            end = binEnd * step - offset
            return beg, end, step

def countsFromBinsAndValues(bins, values):
    beg, end, step = bins
    num = (end - beg) // step
    counts = [0] * num
    for i in values:
        b = (i - beg) // step
        counts[b] += 1
    return counts

def rlist(x):
    return "c(" + ",".join(map(str, x)) + ")"

def ticRange(minVal, maxVal, maxTics=7):
    for i in itertools.count():
        for j in 1, 2, 5:
            step = j * 10 ** i
            minTic = (minVal - 1) // step + 1
            maxTic = maxVal // step
            if maxTic - minTic + 1 <= maxTics:
                return range(minTic * step, maxVal + 1, step)

def stripSuffix(text, s):
    if text.endswith(s):
        return text[:text.rfind(".")]
    return text

def pipe(opts, dest, s):
    if opts.verbose > 1:
        print(s)
    print(s, file=dest.stdin)

def tandemGenotypesPlot(opts, args):
    outFile = args[-1]
    if len(args) == 1:
        outFile = stripSuffix(outFile, ".gz")
        removeMe = ".txt", ".tsv"
        outFile = stripSuffix(outFile, removeMe)
        outFile += ".pdf"
        inFiles = args
    else:
        if not outFile.endswith(".pdf"):
            outFile += ".pdf"
        inFiles = args[:-1]
    results = sorted(readTandemGenotypes(opts, inFiles), reverse=True)
    r = subprocess.Popen(["R", "--slave", "--vanilla"], stdin=subprocess.PIPE,
                         universal_newlines=True)
    pipe(opts, r, 'pdf("{0}", pointsize={1})'.format(outFile, opts.pointsize))
    pipe(opts, r, 'layout(rbind(1:4, 5:8, 9:12, 13:16))')
    pipe(opts, r, 'par(cex=1)')
    pipe(opts, r, 'par(mar=c(1.8, 1.8, 3, 1.8))')
    pipe(opts, r, 'par(mgp=c(3, 0.7, 0))')
    pipe(opts, r, 'par(tcl=-0.4)')
    for res in results[:opts.num]:
        score, chrom, repBeg, repEnd, rep, geneName, genePart, fwd, rev = res
        geneInfo = " ".join(i for i in (geneName, genePart) if i != ".")
        repInfo = rep if len(rep) < 11 else rep[:8] + "..."
        heading1 = repInfo + ": " + geneInfo if geneInfo else repInfo
        heading2 = chrom + ":" + str(repBeg) + "-" + str(repEnd)
        both = sorted(fwd + rev)
        bins = binsFromSortedValues(both)
        fBars = rlist(countsFromBinsAndValues(bins, fwd))
        rBars = rlist(countsFromBinsAndValues(bins, rev))
        maxHeight = max(countsFromBinsAndValues(bins, both))
        beg, end, step = bins
        xTics = ticRange(beg, end - 1)
        yTics = ticRange(0, maxHeight)
        barWidth = 1
        barSpace = 0.2
        gapLen = barSpace * barWidth
        totLen = gapLen + barWidth
        xTicPos = [(i - beg + 0.5) / step * totLen + gapLen / 2 for i in xTics]
        matrix = 'rbind({0}, {1})'.format(fBars, rBars)
        pipe(opts, r, 'barplot({0}, col=c(2,4), axes=FALSE)'.format(matrix))
        pipe(opts, r, 'axis(1, {0}, {1})'.format(rlist(xTicPos), rlist(xTics)))
        pipe(opts, r, 'axis(2, {0})'.format(rlist(yTics)))
        pipe(opts, r, 'mtext("{0}", line=1.5)'.format(heading1))
        pipe(opts, r, 'mtext("{0}", line=0.5)'.format(heading2))

if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # avoid silly error message
    usage = "%prog tandem-genotypes.txt [output.pdf]"
    description = "Draw graphs of tandem-genotypes output."
    op = optparse.OptionParser(usage=usage, description=description)
    op.add_option("-n", "--num", type="int", default=16,
                  help="graph the top NUM repeat regions (default=%default)")
    op.add_option("--pointsize", type="int", default=8, metavar="POINTS",
                  help="text size (default=%default)")
    op.add_option("-v", "--verbose", action="count", default=0,
                  help="show more details")
    opts, args = op.parse_args()
    if not args:
        op.error("please give me a file name")
    tandemGenotypesPlot(opts, args)
