#! /usr/bin/env python
# Copyright 2018 Martin C. Frith

from __future__ import print_function

import gzip
import itertools
import optparse
import signal
import subprocess
import sys

def myOpen(fileName):
    if fileName == "-":
        return sys.stdin
    if fileName.endswith(".gz"):
        return gzip.open(fileName, "rt")  # xxx dubious for Python2
    return open(fileName)

def changesFromText(text):
    if text != ".":
        for i in text.split(","):
            yield int(i.split(":")[0])

def readTandemGenotypes(opts, fileNames):
    for fileName in fileNames:
        for line in myOpen(fileName):
            fields = line.split()
            if fields and line[0] != "#":
                yield fields

def binsFromSortedValues(values):
    maxBins = 50  # xxx ???
    minVal = values[0]
    maxVal = values[-1]
    for s in itertools.count():
        step = s * 2 + 1
        offset = step // 2
        binBeg = (minVal + offset) // step
        binEnd = (maxVal + offset) // step + 1
        if binEnd - binBeg <= maxBins:
            beg = binBeg * step - offset
            end = binEnd * step - offset
            return beg, end, step

def countsFromBinsAndValues(bins, values):
    beg, end, step = bins
    num = (end - beg) // step
    counts = [0] * num
    for i in values:
        b = (i - beg) // step
        counts[b] += 1
    return counts

def rlist(x):
    return "c(" + ",".join(map(str, x)) + ")"

def ticRange(minVal, maxVal, maxTics=7):
    for i in itertools.count():
        for j in 1, 2, 5:
            step = j * 10 ** i
            minTic = (minVal - 1) // step + 1
            maxTic = maxVal // step
            if maxTic - minTic + 1 <= maxTics:
                return range(minTic * step, maxVal + 1, step)

def stripSuffix(text, s):
    if text.endswith(s):
        return text[:text.rfind(".")]
    return text

def pipe(opts, dest, s):
    if opts.verbose:
        print(s)
    print(s, file=dest.stdin)

def layoutRows(numOfRows, numOfCols):
    for i in range(numOfRows):
        j = i * numOfCols
        yield str(j + 1) + ":" + str(j + numOfCols)

def tandemGenotypesPlot(opts, args):
    outFile = args[-1]
    if len(args) == 1:
        outFile = stripSuffix(outFile, ".gz")
        removeMe = ".txt", ".tsv"
        outFile = stripSuffix(outFile, removeMe)
        outFile += ".pdf"
        inFiles = args
    else:
        if not outFile.endswith(".pdf"):
            outFile += ".pdf"
        inFiles = args[:-1]
    r = subprocess.Popen(["R", "--slave", "--vanilla"], stdin=subprocess.PIPE,
                         universal_newlines=True)
    width = opts.cols * 1.75
    height = opts.rows * 1.75
    t = 'pdf("{0}", {1}, {2}, pointsize={3})'
    pipe(opts, r, t.format(outFile, width, height, opts.pointsize))
    layoutRowsText = ",".join(layoutRows(opts.rows, opts.cols))
    pipe(opts, r, 'layout(rbind({0}))'.format(layoutRowsText))
    pipe(opts, r, 'par(cex=1)')
    pipe(opts, r, 'par(mar=c(1.8, 1.8, 3, 1.8))')
    pipe(opts, r, 'par(mgp=c(3, 0.7, 0))')
    pipe(opts, r, 'par(tcl=-0.4)')
    results = readTandemGenotypes(opts, inFiles)
    for res in itertools.islice(results, opts.num):
        chrom, repBeg, repEnd, rep, geneName, genePart, fwd, rev = res[:8]
        geneInfo = " ".join(i for i in (geneName, genePart) if i != ".")
        repInfo = rep if len(rep) < 11 else rep[:8] + "..."
        heading1 = repInfo + ": " + geneInfo if geneInfo else repInfo
        heading2 = chrom + ":" + repBeg + "-" + repEnd
        fwd = sorted(changesFromText(fwd))
        rev = sorted(changesFromText(rev))
        both = sorted(fwd + rev)
        if not both:
            both = [0]
        bins = binsFromSortedValues(both)
        fBars = countsFromBinsAndValues(bins, fwd)
        rBars = countsFromBinsAndValues(bins, rev)
        maxHeight = max(countsFromBinsAndValues(bins, both))
        beg, end, step = bins
        xTics = ticRange(beg, end - 1)
        yTics = ticRange(0, maxHeight)
        barWidthPerSpace = 5
        barStepPerHalfSpace = (barWidthPerSpace + 1) * 2
        barWidth = step * 2 * barWidthPerSpace
        begTicPos = (barWidthPerSpace + 1) + step
        xTicPos = [(i - beg) * barStepPerHalfSpace + begTicPos for i in xTics]
        pipe(opts, r, 'f <- ' + rlist(fBars))
        pipe(opts, r, 'r <- ' + rlist(rBars))
        pipe(opts, r, 'barplot(rbind(f,r), {0}, col=c(2,4), border=NA, '
             'ylim=c(0,{1}), axes=FALSE)'.format(barWidth, maxHeight))
        pipe(opts, r, 'axis(1, {0}, {1})'.format(rlist(xTicPos), rlist(xTics)))
        pipe(opts, r, 'axis(2, {0})'.format(rlist(yTics)))
        pipe(opts, r, 'mtext("{0}", line=1.5)'.format(heading1))
        pipe(opts, r, 'mtext("{0}", line=0.5)'.format(heading2))

if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)  # avoid silly error message
    usage = "%prog tandem-genotypes.txt [output.pdf]"
    description = "Draw graphs of tandem-genotypes output."
    op = optparse.OptionParser(usage=usage, description=description)
    op.add_option("-r", "--rows", type="int", default=4, help=
                  "arrange the graphs in this many rows (default=%default)")
    op.add_option("-c", "--cols", type="int", default=4, help=
                  "arrange the graphs in this many columns (default=%default)")
    op.add_option("-n", "--num", type="int",
                  help="graph the top NUM repeat regions (default=ROWS*COLS)")
    op.add_option("--pointsize", default="8", metavar="POINTS",
                  help="text size (default=%default)")
    op.add_option("-v", "--verbose", action="count", default=0,
                  help="show more details")
    opts, args = op.parse_args()
    if not args:
        op.error("please give me a file name")
    if opts.num is None:
        opts.num = opts.rows * opts.cols
    tandemGenotypesPlot(opts, args)
